##
# Name: Maria E. V. Neptune
# Email:jerenept@gmail.com
# Id: 	004-665-056

build: #make all

tests: #test all

graphs: #graph a;=ll

dist: #make the archive

clean: remove everything

lab2_add: lab2_add.c lab2_utils.c
	gcc -o lab2_add -g -Og -pthread lab2_add.c lab2_utils.c 
